# ---------------------------------------------
# Example of a simple BNF grammar for arithmetic expressions in
# Polish notation (PN)
# ---------------------------------------------

<exp> := <add> | <sub> | <mul> | <div> | <num>;
<add> := + <exp> <exp> ;
<sub> := - <exp> <exp> ;
<mul> := × <exp> <exp> ;
<div> := ÷ <exp> <exp> ;
<num> := ^[0-9]+;
